---
include:
  - board: xiao_ble
    shield: IIIQBall-US_r
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
  - board: xiao_ble
    shield: IIIQBall-US_l
  - board: xiao_ble
    shield: settings_reset